---
title: "Updating_MC_simulation"
author: "Christoph Voelter"
date: "January 24, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(gdata)
```

```{r echo=FALSE}


n.cups=6 #number of cups on the platform
n.trials=2 # number of consecutive trials that need to be correct
memory.size=3 #number of cups remebered that apes chose last
max.trials=8

crit.thresh=n.cups #how many of the cups need to be correct



n.corr.dumb<-function(n.cups){#totally dumb ape
	return(length(unique(sample(n.cups, replace=T)))) ##returns number of unique cups
}

n.corr.smart<-function(n.cups){
	ires=c(rep(0, memory.size), rep(NA, n.cups))
	to.chose=1:n.cups
	lapply(X=(memory.size+1):(memory.size+n.cups), FUN=function(x){
		ires[x]<<-resample(x=setdiff(to.chose, ires[(x-memory.size):(x-1)]), size=1)
	})
	return(length(unique(ires[-(1:memory.size)])))  ##returns number of unique cups
}

```


* plot distribution of the choices  

```{r echo=FALSE}
xx=unlist(lapply(X=rep(n.cups, 10000), FUN=n.corr.smart))
plot(table(xx))
abline(h=500, lty=3)

```



* distribution of number of trials until criterion
```{r}
n.simus=1000
all.res=rep(NA, n.simus)
for(i in 1:n.simus){
	res=unlist(lapply(X=rep(n.cups, n.trials), FUN=n.corr.smart))
	trial.count=n.trials ##starting number of trials
	while(sum(res>=crit.thresh)<n.trials){
		res=c(res[-1], n.corr.smart(n.cups))
		trial.count=trial.count+1
	}
	all.res[i]=trial.count
#	print(i)
}

#save.image("X:/R/EF battery/Updating/ape_simu_6cup.RData")

#significance threshold: number of trials until criterion
quantile(all.res, 0.05)

```

```{r}
##plotting distribution
source("Roger_script/cum_plot.r")
xx=all.res
xx[xx>500]=500
cum.plot(nvec=xx)
```

* p for ape achieving goal at trial 100:
```{r}
func<-function(x){mean(all.res<=x)}
p.values=unlist(lapply(X=n.trials:max.trials, FUN=func))
p.values

```


###when do they make mistakes in the sequence? 

```{r}
n.cups=6 #number of cups on the platform
#n.trials=4 # number of consecutive trials that need to be correct
memory.size=4 #number of cups remebered that apes chose last

#max.trials=8

#crit.thresh=6 #when the first error occurs
```

```{r}
loc.error.dumb<-function(n.cups){#totally dumb ape
	return(anyDuplicated(sample(n.cups, replace=T))) ##position of mistakes in the sequence
}

#plot distribution of the choices
xx=unlist(lapply(X=rep(n.cups, 100000), FUN=loc.error.dumb))
#prop.table(table(xx))

xx<-replace(xx,xx==0,7)#assign value to no error
mean(xx)
```


```{r}

abline(h=50000, lty=3)
###plot proportions

plot(prop.table(table(xx)))
abline(h=0.05, lty=3)

```


```{r}
n.cups=6 #number of cups on the platform
memory.size=c(1:(n.cups)) #number of cups remebered that apes chose last

loc.error.smart<-function(n.cups){
	ires=c(rep(0, memory.size[i]), rep(NA, n.cups))
	to.chose=1:n.cups
	lapply(X=(memory.size[i]+1):(memory.size[i]+n.cups), FUN=function(x){
		ires[x]<<-resample(x=setdiff(to.chose, ires[(x-memory.size[i]):(x-1)]), size=1)
	})
	return(anyDuplicated(ires[-(1:memory.size[i])])) } ##position of mistakes in the sequence

for (i in 1:(n.cups-1)){  
	#plot distribution of the choices
xx=unlist(lapply(X=rep(n.cups, 10000), FUN=loc.error.smart))
#print(prop.table(table(xx)))
xx<-replace(xx,xx==0,7)#assign value to no error
print(mean(xx))
}
```






```{r}
prop.table(table(xx))
plot(table(xx))
abline(h=500, lty=3)

###plot proportions
plot(prop.table(table(xx)))
abline(h=0.05, lty=3)
```


* distribution of errors in sequence



```{r}
n.simus=1000
all.res=rep(NA, n.simus)
for(i in 1:n.simus){
	res=unlist(lapply(X=rep(n.cups, n.trials), FUN=loc.error.smart))
	trial.count=n.trials ##starting number of trials
	while(sum(res>=crit.thresh 	| res<1)<n.trials){
		res=c(res[-1], loc.error.smart(n.cups))
		trial.count=trial.count+1
	}
	all.res[i]=trial.count
	print(i)
}

#significance threshold: number of trials until criterion
quantile(all.res, 0.05)
```

* plotting distribution

```{r}
source("Roger_script/cum_plot.r")
xx=all.res
xx[xx>500]=500
cum.plot(nvec=xx)
```


* p for ape achieving goal at trial 100:

```{r}
func<-function(x){mean(all.res<=x)}
p.values=unlist(lapply(X=n.trials:max.trials, FUN=func))
p.values


```


